# Generated by Django 3.0.7 on 2020-06-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0002_auto_20200623_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
