# Generated by Django 3.0.7 on 2020-06-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0004_auto_20200624_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
