# Generated by Django 3.0.7 on 2020-06-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0005_auto_20200624_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
